### ISSUE TITLE
Newly created plugin test fails (for kepler repository)

### ISSUE THREAD

**Issue by paulvi** [open-archetypes/tycho-eclipse-plugin-archetype#10]
Newly created plugin with `tycho-eclipse-plugin-archetype` archetype has test failing

> [ERROR] Internal error: java.lang.RuntimeException: No solution found because the problem is unsatisfiable.: [Unable to satisfy dependency from tycho-with-maven-open-archetype.test 0.0.1.qualifier to bundle org.junit4 4.5.0.; No solution found because the problem is unsatisfiable.] -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.RuntimeException: No solution found because the problem is unsatisfiable.: [Unable to satisfy dependency from tycho-with-maven-open-archetype.test 0.0.1.qualifier to bundle org.junit4 4.5.0.; No solution found because the problem is unsatisfiable.]

Kepler
`<tycho.version>0.21.0</tycho.version>`

this was discussed before in #3

**Comment by fbricon** [comment]
Can't reproduce with latest snapshot. Make sure the eclipse stream (kepler) is in lower case
