### ISSUE TITLE
GitHub Pages Repository no more existing

### ISSUE THREAD

**Issue by lschuetze** [open-archetypes/tycho-eclipse-plugin-archetype#15]
The given site http://open-archetypes.github.com/maven-repo/release does not exist anymore. GitHub pages is now under `http://${name}.github.io/`.

**Comment by NickVolynkin** [comment]
Indeed, using this URL, I was able to set up an archetype catalog  and build a project with an archetype from it. So it still works for Eclipse.

![screen shot 2015-06-01 at 00 25 37](https://cloud.githubusercontent.com/assets/8015154/7903148/c5ea7dce-07ec-11e5-8d27-66f07a04fe66.png)

**Comment by lschuetze** [comment]
I use this from command line. However, the day I reported this incident I only get a version which defaults to kepler and tycho 0.18. Tried again today and now I get the recent version pulled. Interesting.
Using it with `mvn archetype:generate -DarchetypeCatalog=http://open-archetypes.github.com/maven-repo/releases/`. I will close this as invalid.

**Comment by NickVolynkin** [comment]
Oh, since you're using it from command line, could you please help with writing a help section about that? I've updated some formatting and GUI-instructions. But I'm not enough proficient with command line to make an instruction. Please have a look here: https://github.com/NickVolynkin/tycho-eclipse-plugin-archetype/blob/master/README.md

**Comment by fbricon** [comment]
see
https://github.com/open-archetypes/multi-javaee6-archetype/blob/master/README.md#how-to-use-in-command-line

**Comment by lschuetze** [comment]
Even better with https://github.com/lschuetze/tycho-eclipse-plugin-archetype/commit/9619bc871c08127e16437924eaccfcea1221c7aa no more selecting.

**Comment by fbricon** [comment]
nah, too much typing that way
