### ISSUE TITLE
Build of new project fails on macOS

### ISSUE THREAD

**Issue by avojak** [open-archetypes/tycho-eclipse-plugin-archetype#18]
After creating a new project and running `mvn clean verify` on macOS, building the test module fails on the tycho-surefire-plugin (return code 13) due to missing the `-XstartOnFirstThread` argument. 

Even though this is set in the `macosx` profile via the `<tycho.test.platformArgs>` property, I believe it should instead be set via the `<tycho.test.jvmArgs>` property instead.

**Comment by avojak** [comment]
After taking a look at `src/main/resources/archetype-resources/pom.xml`, I'm thinking it might be due to this check on the Java version (lines 23-28):
```
...
    <tycho.test.platformArgs></tycho.test.platformArgs>
#if ($java_version == "1.6" || $java_version == "1.7")
    <tycho.test.jvmArgs>-Xmx512m -XX:MaxPermSize=256m ${tycho.test.platformArgs}</tycho.test.jvmArgs>
#else
    <tycho.test.jvmArgs>-Xmx512m</tycho.test.jvmArgs>
#end
...
```
I'm using 1.8, which might explain why the pom that was generated without `-XX:MaxPermSize=256m ${tycho.test.platformArgs}`. Any particular reason why this check exists and is limited to 1.6 and 1.7?

**Comment by fbricon** [comment]
[The command line flags PermSize and MaxPermSize have been removed and are ignored](http://www.oracle.com/technetwork/java/javase/8-compatibility-guide-2156366.html). 

Still, `${tycho.test.platformArgs}` should be added to `<tycho.test.jvmArgs>` in all cases

**Comment by fbricon** [comment]
Interesting. I didn't notice the problem earlier because the automated tests pass on all versions of eclipse older than Neon. But running against Neon just fails with org.eclipse.swt.SWTException: Invalid thread access

**Comment by avojak** [comment]
I'm using Neon as well (should've mentioned that in my original comment). The thread access exception sounds like what I would expect when the '-XstartOnFirstThread' arg isn't present.

**Comment by fbricon** [comment]
New 1.0.1 version is available from the http://open-archetypes.github.com/maven-repo/releases/ catalog.
